### ISSUE TITLE
Responsive Image Issue #2

### ISSUE THREAD

**Issue by menardj** [menardj/jesse-menard-portfolio#2]
We almost had it fixed @ericadamski but something went awry. I took the code we touched up that was working in the dev tools, but once I synced it up onto the actual site it didn't work anymore. The images are shrinking and expanding appropriately, but the margin (or padding?) we put isn't appearing anymore. End goal is to have about 3em of padding between each piece when in desktop view and 3em of padding away from edge of phone in mobile view.

@thomasjbradley

![screen shot 2016-11-14 at 7 37 02 pm](https://cloud.githubusercontent.com/assets/6340275/20288535/1c872bce-aaa2-11e6-8206-75a20db64033.png)

**Comment by ericadamski** [comment]
[This](https://github.com/menardj/jesse-menard-portfolio/blob/gh-pages/index.html#L29) needs to have padding on it in order for it to get padded on both the image and the text
